basePath: /api/v0
definitions:
  api.CreateSignatureDeviceResponse:
    properties:
      algorithm:
        type: string
      id:
        type: string
      label:
        type: string
      privateKey:
        type: string
      publicKey:
        type: string
    type: object
  api.ErrorResponse:
    properties:
      errors:
        items:
          type: string
        type: array
    type: object
  api.HealthResponse:
    properties:
      status:
        type: string
      version:
        type: string
    type: object
  api.SignaturedDataResponse:
    properties:
      signature:
        items:
          type: integer
        type: array
      signed_data:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for managing signature devices and signing transactions.
  title: Signing Service API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Evaluates the health of the service and returns a standardized
        response.
      produces:
      - application/json
      responses:
        "200":
          description: Service is healthy
          schema:
            $ref: '#/definitions/api.HealthResponse'
        "405":
          description: Method not allowed
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Check the health of the service
      tags:
      - Health
  /sign/{deviceId}:
    post:
      consumes:
      - application/json
      description: Signs a transaction using the specified device ID and data payload.
      parameters:
      - description: Device ID
        in: path
        name: deviceId
        required: true
        type: string
      - description: Data to be signed
        in: body
        name: data
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Signature successfully generated
          schema:
            $ref: '#/definitions/api.SignaturedDataResponse'
        "400":
          description: Invalid input data
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Device not found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Sign a transaction
      tags:
      - Devices
  /signature-device:
    post:
      consumes:
      - application/json
      description: Creates a new signature device with the specified parameters
      parameters:
      - description: Algorithm (ECC or RSA)
        in: query
        name: algorithm
        required: true
        type: string
      - description: Label for the device
        in: query
        name: label
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.CreateSignatureDeviceResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new signature device
      tags:
      - Devices
swagger: "2.0"
